
modLoader="javafml"
loaderVersion="[49,)"
license="GNU LGPL 3.0"
displayURL="https://teamdiopside.nl/projects/infinitybuttons"
issueTrackerURL="https://github.com/TeamDiopside/InfinityButtons/issues"
[[mods]]
modId="infinitybuttons"
version="${mod_version}"
displayName="Infinity Buttons"
logoFile="icon.png"
authors="LarsMans, curryducker"
description='''A mod which adds new exciting buttons!'''

[[dependencies.infinitybuttons]]
   modId="forge"
   mandatory=true
   versionRange="[49,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.infinitybuttons]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.2,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.infinitybuttons]]
   modId="jade"
   mandatory=false
   versionRange="[9.4.1,)"
   ordering="BEFORE"
   side="BOTH"
[[dependencies.infinitybuttons]]
   modId="atmospheric"
   mandatory=false
   versionRange="[5.0.0,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.infinitybuttons]]
   modId="autumnity"
   mandatory=false
   versionRange="[4.0.0,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.infinitybuttons]]
   modId="buzzier_bees"
   mandatory=false
   versionRange="[5.0.1,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.infinitybuttons]]
   modId="clayworks"
   mandatory=false
   versionRange="[2.0.1,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.infinitybuttons]]
   modId="create"
   mandatory=false
   versionRange="[0.5.1.b,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.infinitybuttons]]
   modId="environmental"
   mandatory=false
   versionRange="[3.0.0,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.infinitybuttons]]
   modId="neapolitan"
   mandatory=false
   versionRange="[4.0.2,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.infinitybuttons]]
   modId="nethersdelight"
   mandatory=false
   versionRange="[1.19-3.0,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.infinitybuttons]]
   modId="quark"
   mandatory=false
   versionRange="[3.3-368,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.infinitybuttons]]
   modId="savageandravage"
   mandatory=false
   versionRange="[5.0.2,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.infinitybuttons]]
   modId="upgrade_aquatic"
   mandatory=false
   versionRange="[5.0.0,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.infinitybuttons]]
   modId="woodworks"
   mandatory=false
   versionRange="[2.0.0,)"
   ordering="AFTER"
   side="BOTH"
