plugins {
    id 'com.github.johnrengelman.shadow'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modImplementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    modImplementation "dev.architectury:architectury-fabric:$rootProject.architectury_api_version"

    modImplementation files('libs/diopside-fabric-1.0.0.jar')
    modRuntimeOnly files('libs/jei-1.21.1-fabric-19.27.0.340.jar')
    modRuntimeOnly files('libs/emi-1.1.24+1.21.1+fabric.jar')

    modCompileOnly files("libs/Jade-1.21.1-Fabric-15.10.5.jar")
    modLocalRuntime files("libs/Jade-1.21.1-Fabric-15.10.5.jar")

    modImplementation "dev.isxander:yet-another-config-lib:${rootProject.yacl_version}-fabric"
    modImplementation "com.terraformersmc:modmenu:${rootProject.modmenu_version}"

    common(project(path: ':common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
    Properties props = new Properties()
    rootProject.file("gradle.properties").withInputStream {
        props.load(it)
    }
    inputs.properties props

    filesMatching('fabric.mod.json') {
        expand rootProject.properties
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    input.set shadowJar.archiveFile
}

fabricApi {
    configureDataGeneration() {
        client = true
        outputDirectory = project.file("$rootDir/common/src/main/generated")
    }
}
