architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"

    modCompileOnly "dev.isxander:yet-another-config-lib:${rootProject.yacl_version}-fabric"

    modImplementation files('libs/diopside-fabric-1.0.0.jar')
}

sourceSets.main.resources.srcDir "src/main/generated"